### ISSUE TITLE
Add a "put" command for SKUs

### ISSUE THREAD

**Issue by CecileRobertMichon** [devigned/pub#10]
Creating new SKUs is going to be key for automating image publishing for capi, would be great to be able to create a new SKU from the CLI tool when it doesn't exist.

**Comment by devigned** [comment]
I'll add this. I was thinking about doing it, but held off on it to just use PUT on Offer rather than a SKU (Plan).

It definitely would be easier to add a SKU individually.

@CecileRobertMichon, would you specify the plan with an ID, and a file or a blob of json?

something like: `pub sku corevm put -n $sku_name -r $regions -f $file_path_to_plan_details_json`

**Comment by marosset** [comment]
i'm working on this now :)

**Comment by marosset** [comment]
@devigned how about just taking in all the details (name, regions, corevm/vmimage) through the json file?
Build pipelines using this can start with json template files and complete them using jq/other scripting before calling pub.
I think that would keep the implementation in pub a cleaner.

**Comment by devigned** [comment]
@marosset I'm up for that implementation, but I think you might run into issues with marshaling the correct structure from the json input.

**Comment by devigned** [comment]
Added with #13
